project:
  workdir: "/Users/hiro/PycharmProjects/turn-taking-working"
io:
  epoch_dir: "/Volumes/work-4T/hyperscanning/derived/eeg/epochs"
  epoch_pattern: "{subject}_task-{task}_run-{run}_epochs-epo.fif"
  out_dir: "/Volumes/work-4T/turn-taking-new"
dataset:
  subjects:
    mode: "from_epochs"
    exclude:
    - "sub-001"
    - "sub-002"
    - "sub-003"
    - "sub-032"
    include: []
  tasks:
  - "conversation"
  runs:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  invalid_subject_run:
  - - "sub-004"
    - '1'
  - - "sub-004"
    - '2'
  - - "sub-027"
    - '8'
  - - "sub-028"
    - '8'
  - - "sub-015"
    - '3'
constraints:
  min_latency: -1.0
  max_latency: 1.0
  min_response_duration: 0.01
analysis:
  contrasts:
  - "duration"
  - "latency"
  bands:
  - "alpha"
  - "beta"
  erp:
    left_margin: 0.2
    right_margin: 0.5
    sfreq: 512
    n_permutations: 1000
    threshold: null
  tfr:
    left_margin: 0.2
    right_margin: 0.5
    method: "hilbert"
    sfreq: 512
    n_permutations: 1000
    threshold: null
  mixed:
    tw1:
    - -1.3
    - -0.7
    tw2:
    - -0.7
    - 0.0
    baseline:
    - -2.0
    - 0.5
  decoding:
    sfreq: 64
    n_splits: 10
    n_permutations: 1000
    threshold: null
    left_margin: 0.2
    right_margin: 0.5
execution:
  threads_light: 1
  threads_heavy: 10
  mem_mb_light: 1000
  mem_mb_heavy: 10000
