[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "turntaking"
version = "0.0.0"
description = "Turn-taking analysis package (skeleton)"
requires-python = ">=3.10"

dependencies = [
  "h5py",
  "mne",
  "numpy",
  "pandas",
  "pyarrow >= 14.0",
  "seaborn",
  "cairosvg",
  "pillow"
]

[project.optional-dependencies]
test = [
  "pytest>=8.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
